---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "eventlet"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
