addons:
  apt:
    update: true
    packages:
      - cppcheck
before_install:
  - export PATH=$PATH:~/bin
install:
  - curl -fsSL http://downloads.arduino.cc/arduino-1.8.10-linux64.tar.xz | tar Jxf -
  - ln -s ~/arduino*/arduino ~/bin/arduino
  - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=~/bin sh
  - arduino-cli config init
  - arduino-cli core update-index
  - arduino-cli core install arduino:sam
  - arduino-cli lib install ArduinoSTL
  - arduino-cli lib install DueTimer
  - arduino-cli lib install FixedPoints
  - arduino-cli lib install "MIDI Library"
script:
  - cppcheck --enable=all --language=c++ --error-exitcode=1 --xml --inline-suppr --check-config *cpp *h *ino
  - arduino-cli compile --verbose --fqbn arduino:sam:arduino_due_x chime_red2.ino
