name: test
on: [push, pull_request]
jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-platform: ["arduino:sam", "arduino:samd"]
        include:
          - arduino-platform: "arduino:sam"
            fqbn: "arduino:sam:arduino_due_x"
          - arduino-platform: "arduino:samd"
            fqbn: "arduino:samd:arduino_zero_edbg"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: |
          ./build.sh ${{ matrix.arduino-platform }} ${{ matrix.fqbn }}
